# Project Information
site_name: Liferay Learn
site_description: Liferay Learn - Intuitive, Readable, and Practical Resources for Learning Liferay

# Repository
repo_url: https://github.com/jrhoun/jrhoun-help/
edit_uri: edit/read-the-docs-testing/docs

# Copyright
copyright: 'Copyright &copy; 2019 - Liferay, Inc.'

# Configuration
theme: 
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  # logo:
  #     icon: 'menu_book'
  #     logo: 'images/liferay-logo-full-color.svg'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true

# Navigation

# nav:
  # - Liferay Learn: 'README.md'
  # - Analytics Cloud: analytics-cloud/README.md
  # - Commerce: 
  #     - Getting Started: commerce/README.md
  #     - User Guide: commerce/user-guide/README.md
  #     - Developer Guide: commerce/developer-guide/README.md
  #     - Installation and Upgrades: commerce/installation-and-upgrades/README.md
  #     - Get Help: commerce/get-help/README.md
  # - DXP: 
  #     - Getting Started: dxp/README.md
  # - DXP Cloud: 
  #     - Getting Started: dxp-cloud/README.md
  # - Other Projects: 
  #     - Getting Started: other-projects/README.md